### ISSUE TITLE
The `shape` should be specified when creating a node/edge instance

### ISSUE THREAD

**Issue by john100ster** [lloydzhou/antv-x6-react-practice#5]
兄弟，麻烦问一下，如何使用 register，
 报错：The `shape` should be specified when creating a node/edge instance
![image](https://user-images.githubusercontent.com/23519347/234752726-276803d7-f6ec-47e5-8c3d-817935c179bb.png)

![image](https://user-images.githubusercontent.com/23519347/234752610-46f1575f-5827-4c95-8426-744deaac1b56.png)
import { register } from "@antv/x6-react-shape"
我在 graph.tsx 这个文件里加的register

**Comment by lloydzhou** [comment]
这个register最好移到组件外面。
看你的写法应该是hooks的写法，这个函数每渲染一次就会执行一次register，应该会造成很大的浪费

另外，你调用了fromJSON，必须确保执行fromJSON之前这些节点都已经注册好了。否则就会出现你截图的错误
